'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Account={contact:string;phone:string;email:string};
type Job={id:string;title:string;department:string;city:string;status:string};
type Candidate={id:string;jobId:string|null;name:string;role:string;company:string;stage:string;phone:string;email:string};
type Interview={id:string;candidateId:string;scheduledAt:string;round:string;mode:string;interviewer:string;status:string;createdAt:string;updatedAt:string};
type Dataset={account:Account;jobs:Job[];candidates:Candidate[];interviews:Interview[]};
const statuses=['待确认','已确认','已完成','已取消'];
const menuItems=[{icon:'◉',label:'候选人筛选',href:'/interviewer-candidate'},{icon:'▤',label:'人工评估',href:'/assessment'},{icon:'▣',label:'面试管理',href:'/interview-management'},{icon:'▥',label:'招聘进展',href:'/recruitment-progress'},{icon:'⚙',label:'设置',href:'/workbench'}];

export default function InterviewManagementClient(){
  const [data,setData]=useState<Dataset|null>(null);const [error,setError]=useState('');const [keyword,setKeyword]=useState('');const [status,setStatus]=useState('全部');const [jobId,setJobId]=useState('');const [date,setDate]=useState('');const [modal,setModal]=useState(false);const [saving,setSaving]=useState(false);const [toast,setToast]=useState('');
  async function load(){const response=await fetch('/api/workbench',{cache:'no-store'});if(response.status===401){window.location.assign('/');return}if(!response.ok)throw new Error('load');setData(await response.json() as Dataset)}
  useEffect(()=>{void load().catch(()=>setError('面试数据加载失败，请稍后刷新。'))},[]);
  const visible=useMemo(()=>data?.interviews.filter(item=>{const person=data.candidates.find(candidate=>candidate.id===item.candidateId);const text=`${person?.name||''}${person?.role||''}${item.interviewer}${item.round}${item.mode}`.toLowerCase();return(!keyword||text.includes(keyword.toLowerCase()))&&(status==='全部'||item.status===status)&&(!jobId||person?.jobId===jobId)&&(!date||localDate(item.scheduledAt)===date)}).sort((a,b)=>new Date(a.scheduledAt).getTime()-new Date(b.scheduledAt).getTime())||[],[data,keyword,status,jobId,date]);
  function flash(message:string){setToast(message);window.setTimeout(()=>setToast(''),2200)}
  async function updateStatus(id:string,value:string){const response=await fetch('/api/workbench',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'interviewStatus',id,value})});if(!response.ok){flash('保存失败');return}await load();flash('保存成功')}
  async function createInterview(event:FormEvent<HTMLFormElement>){event.preventDefault();if(saving)return;setSaving(true);const form=new FormData(event.currentTarget);const scheduledAt=new Date(`${form.get('date')}T${form.get('time')}`).toISOString();try{const response=await fetch('/api/workbench',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resource:'interview',payload:{candidateId:form.get('candidateId'),scheduledAt,round:form.get('round'),mode:form.get('mode')}})});if(!response.ok){flash('保存失败');return}setModal(false);await load();flash('保存成功')}catch{flash('保存失败')}finally{setSaving(false)}}
  if(!data)return <Loading error={error}/>;
  const today=localDate(new Date().toISOString());
  return <main className="interviewer-page"><Sidebar active="面试管理"/><section className="interviewer-main"><Header title="面试管理" account={data.account} keyword={keyword} setKeyword={setKeyword}/><Crumbs title="面试管理"/>
    <div className="hr-module-content"><section className="hr-module-hero"><div><p>INTERVIEW SCHEDULE</p><h2>面试日程</h2><span>集中管理候选人面试安排、确认和结果状态</span></div><button type="button" onClick={()=>setModal(true)}>＋ 安排面试</button></section>
      <section className="hr-kpi-row">{[['全部面试',data.interviews.length],['今日面试',data.interviews.filter(item=>localDate(item.scheduledAt)===today).length],['待确认',data.interviews.filter(item=>item.status==='待确认').length],['待补结果',data.interviews.filter(item=>new Date(item.scheduledAt)<new Date()&&!['已完成','已取消'].includes(item.status)).length]].map(item=><article key={String(item[0])}><span>{item[0]}</span><b>{item[1]}</b></article>)}</section>
      <section className="hr-filter-bar"><select value={status} onChange={event=>setStatus(event.target.value)}><option>全部</option>{statuses.map(item=><option key={item}>{item}</option>)}</select><select value={jobId} onChange={event=>setJobId(event.target.value)}><option value="">全部职位</option>{data.jobs.map(job=><option key={job.id} value={job.id}>{job.title}</option>)}</select><input type="date" value={date} onChange={event=>setDate(event.target.value)}/><button type="button" onClick={()=>{setStatus('全部');setJobId('');setDate('');setKeyword('')}}>重置筛选</button><span>共 {visible.length} 场</span></section>
      <section className="hr-record-card"><header><h3>面试安排</h3><span>按计划时间排序</span></header><div className="hr-record-list">{visible.length?visible.map(item=>{const person=data.candidates.find(candidate=>candidate.id===item.candidateId);const job=data.jobs.find(value=>value.id===person?.jobId);return <article className="interview-manage-row" key={item.id}><time><b>{formatTime(item.scheduledAt)}</b><span>{formatDate(item.scheduledAt)}</span></time><i/><div><p>{item.round} · {item.mode}</p><h3>{person?.name||'候选人已移除'}<span>{job?.title||person?.role||'未关联职位'}</span></h3><small>面试官：{item.interviewer||data.account.contact}</small></div><div className="interview-meta"><span>{new Date(item.scheduledAt)<new Date()?'已到面试时间':'尚未开始'}</span><small>更新时间 {formatDate(item.updatedAt)}</small></div><select value={item.status} onChange={event=>void updateStatus(item.id,event.target.value)}>{statuses.map(value=><option key={value}>{value}</option>)}</select></article>}):<Empty title="暂无面试安排" text="调整筛选条件，或为候选人创建新的面试日程。"/>}</div></section>
    </div></section>{modal&&<div className="assessment-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setModal(false)}}><form className="assessment-modal interview-create-modal" onSubmit={createInterview}><button type="button" className="assessment-modal-close" onClick={()=>setModal(false)}>×</button><p>NEW INTERVIEW</p><h2>安排面试</h2><small>新日程将保存到当前账号并同步至招聘工作台</small><label>候选人<select required name="candidateId" defaultValue=""><option value="" disabled>请选择候选人</option>{data.candidates.map(person=><option key={person.id} value={person.id}>{person.name} · {person.role}</option>)}</select></label><div className="hr-form-grid"><label>日期<input required name="date" type="date" min={today}/></label><label>时间<input required name="time" type="time" step="300"/></label></div><div className="hr-form-grid"><label>面试轮次<input name="round" placeholder="例如：业务一面"/></label><label>面试方式<select name="mode" defaultValue="视频面试"><option>视频面试</option><option>电话面试</option><option>线下面试</option></select></label></div><footer><button type="button" onClick={()=>setModal(false)}>取消</button><button type="submit" disabled={saving}>{saving?'保存中…':'保存面试'}</button></footer></form></div>}{toast&&<div className="interviewer-toast">{toast}</div>}</main>;
}

function Sidebar({active}:{active:string}){return <aside className="interviewer-rail"><a className="interviewer-logo" href="/workbench"><span>星</span><b>星鉴人才<small>HIRING DEPARTMENT</small></b></a><p className="interviewer-role-label">HR 工作台</p><nav>{menuItems.map(item=><a key={item.label} className={item.label===active?'active':''} href={item.href}><i>{item.icon}</i><span>{item.label}</span></a>)}</nav><button type="button">«</button></aside>}
function Header({title,account,keyword,setKeyword}:{title:string;account:Account;keyword:string;setKeyword:(value:string)=>void}){return <header className="interviewer-header"><div className="interviewer-heading"><h1>{title}</h1><small>HR 候选人工作台</small></div><div className="interviewer-tools"><div className="interviewer-global-search"><input value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="搜索候选人、职位或面试官"/><button type="button">⌕</button></div><span className="interviewer-avatar">{account.contact.slice(0,1)}</span><div className="interviewer-account-copy"><b>{account.contact}</b><small>HR 招聘</small></div></div></header>}
function Crumbs({title}:{title:string}){return <div className="interviewer-open-tabs"><a href="/interviewer-candidate">候选人筛选</a><i>›</i><button type="button" className="active">{title}</button><span>当前角色：HR</span></div>}
function Loading({error}:{error:string}){return <main className="interviewer-loading"><span>星</span><b>{error||'正在读取数据…'}</b>{error&&<button onClick={()=>window.location.reload()}>重新加载</button>}</main>}
function Empty({title,text}:{title:string;text:string}){return <div className="interviewer-empty"><span>◷</span><b>{title}</b><p>{text}</p></div>}
function localDate(value:string){const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?'-':`${date.getMonth()+1}月${date.getDate()}日`}
function formatTime(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?'--:--':`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`}
